# EMR系统的Docker Compose配置文件
# 本文件定义了电子病历(EMR)系统所需的所有微服务及其配置

services:
  # RocketMQ名称服务器配置
  # 负责维护主题的路由信息，提供服务发现和故障转移支持
#  rocketmq-nameserver:
#    image: apache/rocketmq:4.9.4  # 使用Apache RocketMQ 4.9.4版本镜像
#    container_name: rocketmq-nameserver  # 容器名称
#    command: sh mqnamesrv  # 启动名称服务器
#    ports:
#      - "9876:9876"  # 暴露命名服务器端口用于服务注册和发现
#    volumes:
#      - rocketmq_namesrv_data:/home/rocketmq/data  # 数据持久化
#      - rocketmq_namesrv_logs:/home/rocketmq/logs  # 日志持久化
#    restart: unless-stopped  # 容器停止时自动重启，除非手动停止
#    networks:
#      - emr-net  # 连接到EMR网络
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'  # 限制CPU使用率
#          memory: 1G   # 限制内存使用

  # RocketMQ消息代理服务配置
  # 负责消息的存储、投递和高可用性保证
#  rocketmq-broker:
#    image: apache/rocketmq:4.9.4  # 使用Apache RocketMQ 4.9.4版本镜像
#    container_name: rocketmq-broker  # 容器名称
#    command: sh mqbroker -n rocketmq-nameserver:9876 autoCreateTopicEnable=true  # 启动代理并连接到名称服务器，允许自动创建主题
#    depends_on:
#      - rocketmq-nameserver  # 依赖于名称服务器，确保名称服务器先启动
#    environment:
#      JAVA_OPTS: -Drocketmq.broker.ip=broker  # Java启动选项，设置代理IP
#      TZ: Asia/Shanghai  # 设置时区为上海，确保时间同步
#    ports:
#      - "10909:10909"  # 客户端连接端口
#      - "10911:10911"  # 生产者连接端口
#      - "10912:10912"  # 管理端口
#    volumes:
#      - rocketmq_broker_data:/home/rocketmq/data  # 数据持久化
#      - rocketmq_broker_logs:/home/rocketmq/logs  # 日志持久化
#    restart: unless-stopped  # 容器停止时自动重启，除非手动停止
#    networks:
#      - emr-net  # 连接到EMR网络
#    deploy:
#      resources:
#        limits:
#          cpus: '1'  # 限制CPU使用率
#          memory: 1.5G  # 限制内存使用
  rabbitmq:
    image: "bitnami/rabbitmq:latest"
    container_name: "rabbitmq"
    restart: "always"
    environment:
      - "RABBITMQ_USERNAME=admin"
      - "RABBITMQ_PASSWORD=B21031618rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"
    deploy:
      resources:
        limits:
          cpus: '1'  # 限制CPU使用率
          memory: 1G  # 限制内存使用
  # MySQL数据库服务配置
  # 提供关系型数据存储，用于持久化EMR系统中的结构化数据
  mysql:
    command:
      - "mysqld"  # MySQL服务器启动命令
    container_name: "mysql"  # 容器名称
    environment:
      - "TZ=Asia/Shanghai"  # 设置时区为上海
      - "MYSQL_ROOT_PASSWORD=B21031618root"  # 设置MySQL root用户密码
    image: "mysql"  # 使用MySQL官方镜像
    networks:
      - "emr-net"  # 连接到EMR网络
    ports:
      - "3306:3306/tcp"  # 暴露MySQL标准端口
    volumes:
      - "mysql_data:/var/lib/mysql"  # 数据持久化

  # Nacos服务配置
  # 提供动态服务发现、配置管理和服务治理能力
  nacos:
    container_name: "nacos"  # 容器名称
    environment:
      - "MODE=standalone"  # 单机模式部署
      - "TIME_ZONE=Asia/Shanghai"  # 设置时区为上海
    image: "nacos/nacos-server:v2.1.2"  # 使用Nacos 2.1.2版本镜像
    networks:
      - "emr-net"  # 连接到EMR网络
    ports:
      - "8848:8848/tcp"  # 暴露Nacos服务端口
      - "9848:9848/tcp"  # 暴露Nacos集群通信端口
    deploy:
      resources:
        limits:
          memory: 1G  # 限制内存使用

  # Redis服务配置
  # 提供高性能的键值存储，用于缓存、会话管理和发布/订阅功能
  redis:
    command:
      - "redis-server"  # Redis服务器启动命令
      - "--requirepass"  # 设置密码参数
      - "B21031618redis"  # Redis访问密码
    container_name: "redis"  # 容器名称
    environment:
      - "REDIS_VERSION=7.4.2"  # Redis版本
    image: "redis"  # 使用Redis官方镜像
    networks:
      - "emr-net"  # 连接到EMR网络
    ports:
      - "6379:6379/tcp"  # 暴露Redis标准端口
    volumes:
      - "redis_data:/data"  # 数据持久化

# 定义持久化存储卷
volumes:
  rocketmq_namesrv_data:  # RocketMQ名称服务器数据卷，确保重启后数据不丢失
  rocketmq_namesrv_logs:  # RocketMQ名称服务器日志卷，用于问题排查
  rocketmq_broker_data:   # RocketMQ消息代理数据卷，存储消息队列数据
  rocketmq_broker_logs:   # RocketMQ消息代理日志卷，用于问题排查和监控
  mysql_data:  # MySQL数据卷
  redis_data: # Redis数据卷
  rabbitmq_data:


# 定义网络
networks:
  emr-net:
    driver: bridge  # 使用桥接模式，允许容器之间相互访问

version: "3.6"  # 使用Docker Compose文件格式版本3.6


