server:
  port: 8087
# ??????
spring:
  application:
    name: emr-evaluation-services  # ??????????????
  # ???????
  datasource:
    url: jdbc:mysql://118.145.210.214:3306/emr  # MySQL???????
    username: root  # ??????
    password: B21031618root  # ?????
    driver-class-name: com.mysql.cj.jdbc.Driver  # ???????
  # Redis????
  data:
    redis:
      host: 118.145.210.214  # Redis?????
      port: 6379  # Redis?????
      password: B21031618redis  # Redis????
  # Nacos???????????
  cloud:
    nacos:
      discovery:
        server-addr: 118.145.210.214:8848  # Nacos?????
      username: nacos  # Nacos?????
      password: B21031618nacos  # Nacos????
  rabbitmq:
    host: 118.145.210.214
    port: 5672 # 端口
    username: B21031618 # 用户名
    password: B21031618rabbitmq # 密码
    virtual-host: /
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息

# MyBatis-Plus??
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  # ???????
      logic-delete-value: 1  # ???????????
      logic-not-delete-value: 0  # ???????
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL????????

# ???????
framework:
  fastjson:
    safa-mode: true  # FastJSON??????
  cache:
    redis:
      value-timeout: 50000  # Redis??????????
      bloom-filter:
        user-register: null

baidu:
  api:
    app-id: "118741243"
    api-key: "FsnkwpmvAx5piCQpHQ6EyiyY"
    secret-key: "7TwJGgtjA5e2Kc2HbD3m5gwcAX9uKkc0"
