spring:
  cloud:
    gateway:
      routes:
        - id: emr-user-services
          uri: lb://emr-user-services/api/user-services/**
          predicates:
            - Path=/api/user-services/**

        - id: emr-booking-services
          uri : lb://emr-booking-services/api/booking-services/**
          predicates:
            - Path=/api/booking-services/**
          filters:
            - name: GeneralServicesFilter

        - id: emr-department-services
          uri: lb://emr-department-services/api/department-services/**
          predicates:
            - Path=/api/department-services/**
          filters:
            - name: GeneralServicesFilter

        - id: emr-emr-services
          uri: lb://emr-emr-services/api/emr-services/**
          predicates:
            - Path=/api/emr-services/**
          filters:
            - name: GeneralServicesFilter

        - id: emr-evaluation-services
          uri: lb://emr-evaluation-services/api/evaluation-services/**
          predicates:
            - Path=/api/evaluation-services/**
          filters:
            - name: GeneralServicesFilter

        - id: emr-notice-services
          uri: lb://emr-notice-services/api/notice-services/**
          predicates:
            - Path=/api/notice-services/**
          filters:
            - name: GeneralServicesFilter

        - id: emr-registration-services
          uri: lb://emr-registration-services/api/registration-services/**
          predicates:
            - Path=/api/registration-services/**
          filters:
            - name: GeneralServicesFilter
emr:
  general-services:
    path-permissions:
    #预约时间表
      # 创建预约时间
      "/api/booking-services/v1/create": ["doctor","admin"]
      #根据id删除预约时间表
      "/api/booking-services/v1/delete": ["doctor","admin"]
      #更新预约时间表
      "/api/booking-services/v1/update": ["doctor","admin"]
      #根据id查询时间表
      "/api/booking-services/v1/queryById": ["doctor","patient","admin"]
      #根据医生id查询时间表
      "/api/booking-services/v1/queryByDoctorId": ["doctor","patient","admin"]
    #科室管理
      #新增科室
      "/api/department-services/v1/create": ["admin"]
      #删除科室
      "/api/department-services/v1/delete": ["admin"]
      #更新科室
      "/api/department-services/v1/update": ["admin"]
      #根据id查询科室
      "/api/department-services/v1/queryById": ["admin","doctor","patient"]
      #查询所有科室
      "/api/department-services/v1/queryAll": ["admin","doctor","patient","guest"]
    #病历管理
      #新增病历
      "/api/emr-services/v1/create": ["doctor"]
      #删掉病历
      "/api/emr-services/v1/delete": ["doctor","patient"]
      #更新病历
      "/api/emr-services/v1/update": ["doctor"]
      #id查询病历
      "/api/emr-services/v1/queryById": ["doctor","admin","patient"]
    #就诊评价
      #新增评价
      "/api/evaluation-services/v1/create": ["patient"]
      #删除评价
      "/api/evaluation-services/v1/delete": ["patient"]
      #id 查询
      "/api/evaluation-services/v1/queryById": ["patient","admin","doctor"]
      # 病历id查询
      "/api/evaluation-services/v1/queryByEmrId" : ["patient","admin","doctor"]
    #公告管理
      #新增公告
      "/api/notice-services/v1/create": ["admin"]
      # 删除
      "/api/notice-services/v1/delete": ["admin"]
      #改
      "/api/notice-services/v1/update": ["admin"]
      #查询
      "/api/notice-services/v1/queryById": ["admin","doctor","patient","guest"]
    #挂号管理
      #新增挂号
      "/api/registration-services/v1/create": ["patient"]
      #删除挂号
      "/api/registration-services/v1/delete": ["patient"]
      #修改挂号
      "/api/registration-services/v1/update": ["patient"]
      #id 查询
      "/api/registration-services/v1/queryById": ["admin","patient","doctor"]
      #完成挂号
      "/api/registration-services/v1/finish": ["admin","patient","doctor"]

    # 是否启用严格模式(未明确配置的路径将被拒绝)
    strict-mode: true
  user-services:
    path-permissions:
      "root":
        "root": ["/api/user-services/v1/query","/api/user-services/v1/actual/query","/api/user-services/v1/has-username","/api/user-services/v1/has-username","/api/user-services/v1/update","/api/user-services/v1/login","/api/user-services/v1/check-login","/api/user-services/v1/logout"]
        "admin":  ["/api/user-services/v1/query","/api/user-services/v1/actual/query","/api/user-services/v1/has-username","/api/user-services/v1/has-username","/api/user-services/v1/register","/api/user-services/v1/update"]
        "doctor": ["/api/user-services/v1/query","/api/user-services/v1/actual/query","/api/user-services/v1/has-username","/api/user-services/v1/has-username","/api/user-services/v1/register","/api/user-services/v1/update","/api/user-services/v1/login","/api/user-services/v1/check-login"]
        "patient": ["/api/user-services/v1/query","/api/user-services/v1/actual/query","/api/user-services/v1/has-username","/api/user-services/v1/has-username"]
      "admin":
        "admin": ["/api/user-services/v1/query","/api/user-services/v1/actual/query","/api/user-services/v1/has-username","/api/user-services/v1/has-username","/api/user-services/v1/update","/api/user-services/v1/login","/api/user-services/v1/check-login","/api/user-services/v1/logout"]
        "doctor":  ["/api/user-services/v1/query","/api/user-services/v1/actual/query","/api/user-services/v1/has-username","/api/user-services/v1/has-username","/api/user-services/v1/register","/api/user-services/v1/update"]
        "patient": ["/api/user-services/v1/query","/api/user-services/v1/actual/query","/api/user-services/v1/has-username","/api/user-services/v1/has-username","/api/user-services/v1/update","/api/user-services/v1/check-login"]
       # 医生只有自己的全部权限和查看用户
        # 医生账户不能自行注册，只有管理员可以注册医生账户
      "doctor":
        "doctor": ["/api/user-services/v1/query","/api/user-services/v1/actual/query","/api/user-services/v1/has-username","/api/user-services/v1/has-username","/api/user-services/v1/register","/api/user-services/v1/update","/api/user-services/v1/login","/api/user-services/v1/check-login","/api/user-services/v1/logout"]
        "patient": ["/api/user-services/v1/query"]
      # 患者只有自己的全部功能和查看医生信息
      "patient":
        "doctor": ["/api/user-services/v1/query"]
        "patient": ["/api/user-services/v1/query","/api/user-services/v1/actual/query","/api/user-services/v1/has-username","/api/user-services/v1/has-username","/api/user-services/v1/register","/api/user-services/v1/update","/api/user-services/v1/login","/api/user-services/v1/check-login","/api/user-services/v1/logout"]
        # 游客只能登录 和注册患者账户
      "guest":
        "root": ["/api/user-services/v1/login"]
        "admin": ["/api/user-services/v1/login"]
        "doctor": ["/api/user-services/v1/login"]
        "patient": ["/api/user-services/v1/login","/api/user-services/v1/register"]
    # 是否启用严格模式(未明确配置的路径将被拒绝)
    strict-mode: true

