server:
  port: 8086
spring:
  application:
    name: emr-notice-services
  datasource:
    url: jdbc:mysql://118.145.210.214:3306/emr
    username: root
    password: B21031618root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 118.145.210.214
      port: 6379
      password: B21031618redis

  cloud:
    nacos:
      discovery:
        server-addr: 118.145.210.214:8848
      username: nacos
      password: B21031618nacos


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


framework:
  fastjson:
    safa-mode: true
  cache:
    redis:
      value-timeout: 50000
      bloom-filter:
        user-register: null